export const parkingSlot = [
  {
    id: 1,
    name: "A1",
    occupied: false,
    distances: [3, 6, 4],
    size: 1,
  },
  {
    id: 2,
    name: "A2",
    occupied: false,
    distances: [4, 4, 1],
    size: 0,
  },
  {
    id: 3,
    name: "A3",
    occupied: false,
    distances: [1, 7, 5],
    size: 0,
  },
  {
    id: 4,
    name: "A4",
    occupied: false,
    distances: [4, 7, 7],
    size: 1,
  },
  {
    id: 5,
    name: "A5",
    occupied: false,
    distances: [5, 4, 6],
    size: 0,
  },
  {
    id: 6,
    name: "A6",
    occupied: false,
    distances: [5, 3, 7],
    size: 2,
  },
  {
    id: 7,
    name: "A7",
    occupied: false,
    distances: [5, 1, 6],
    size: 2,
  },
  {
    id: 8,
    name: "A8",
    occupied: false,
    distances: [6, 4, 1],
    size: 0,
  },
  {
    id: 9,
    name: "A9",
    occupied: false,
    distances: [5, 3, 3],
    size: 0,
  },
  {
    id: 10,
    name: "A10",
    occupied: false,
    distances: [3, 2, 3],
    size: 2,
  },
  {
    id: 11,
    name: "B1",
    occupied: false,
    distances: [7, 4, 6],
    size: 1,
  },
  {
    id: 12,
    name: "B2",
    occupied: false,
    distances: [6, 5, 7],
    size: 2,
  },
  {
    id: 13,
    name: "B3",
    occupied: false,
    distances: [4, 7, 4],
    size: 2,
  },
  {
    id: 14,
    name: "B4",
    occupied: false,
    distances: [7, 6, 3],
    size: 2,
  },
  {
    id: 15,
    name: "B5",
    occupied: false,
    distances: [7, 2, 5],
    size: 0,
  },
  {
    id: 16,
    name: "B6",
    occupied: false,
    distances: [5, 5, 7],
    size: 0,
  },
  {
    id: 17,
    name: "B7",
    occupied: false,
    distances: [2, 2, 1],
    size: 2,
  },
  {
    id: 18,
    name: "B8",
    occupied: false,
    distances: [3, 1, 2],
    size: 1,
  },
  {
    id: 19,
    name: "B9",
    occupied: false,
    distances: [6, 4, 1],
    size: 0,
  },
  {
    id: 20,
    name: "B10",
    occupied: false,
    distances: [1, 7, 4],
    size: 0,
  },
  {
    id: 21,
    name: "C1",
    occupied: false,
    distances: [2, 2, 3],
    size: 0,
  },
  {
    id: 22,
    name: "C2",
    occupied: false,
    distances: [7, 5, 4],
    size: 2,
  },
  {
    id: 23,
    name: "C3",
    occupied: false,
    distances: [4, 2, 3],
    size: 1,
  },
  {
    id: 24,
    name: "C4",
    occupied: false,
    distances: [5, 4, 4],
    size: 1,
  },
  {
    id: 25,
    name: "C5",
    occupied: false,
    distances: [2, 7, 4],
    size: 2,
  },
  // {
  //   id: 26,
  //   name: "C6",
  //   occupied: false,
  //   distances: [5, 4, 6],
  //   size: 2,
  // },
  // {
  //   id: 27,
  //   name: "C7",
  //   occupied: false,
  //   distances: [7, 7, 4],
  //   size: 2,
  // },
  // {
  //   id: 28,
  //   name: "C8",
  //   occupied: false,
  //   distances: [7, 5, 2],
  //   size: 1,
  // },
  // {
  //   id: 29,
  //   name: "C9",
  //   occupied: false,
  //   distances: [1, 5, 2],
  //   size: 0,
  // },
  // {
  //   id: 30,
  //   name: "C10",
  //   occupied: false,
  //   distances: [6, 2, 3],
  //   size: 1,
  // },
  // {
  //   id: 31,
  //   name: "D1",
  //   occupied: false,
  //   distances: [6, 1, 3],
  //   size: 2,
  // },
  // {
  //   id: 32,
  //   name: "D2",
  //   occupied: false,
  //   distances: [5, 1, 3],
  //   size: 1,
  // },
  // {
  //   id: 33,
  //   name: "D3",
  //   occupied: false,
  //   distances: [3, 1, 6],
  //   size: 2,
  // },
  // {
  //   id: 34,
  //   name: "D4",
  //   occupied: false,
  //   distances: [4, 6, 2],
  //   size: 1,
  // },
  // {
  //   id: 35,
  //   name: "D5",
  //   occupied: false,
  //   distances: [6, 1, 1],
  //   size: 0,
  // },
  // {
  //   id: 36,
  //   name: "D6",
  //   occupied: false,
  //   distances: [4, 2, 5],
  //   size: 2,
  // },
  // {
  //   id: 37,
  //   name: "D7",
  //   occupied: false,
  //   distances: [4, 5, 4],
  //   size: 0,
  // },
  // {
  //   id: 38,
  //   name: "D8",
  //   occupied: false,
  //   distances: [2, 7, 5],
  //   size: 2,
  // },
  // {
  //   id: 39,
  //   name: "D9",
  //   occupied: false,
  //   distances: [2, 4, 5],
  //   size: 0,
  // },
  // {
  //   id: 40,
  //   name: "D10",
  //   occupied: false,
  //   distances: [6, 7, 6],
  //   size: 1,
  // },
  // {
  //   id: 41,
  //   name: "E1",
  //   occupied: false,
  //   distances: [1, 4, 6],
  //   size: 0,
  // },
  // {
  //   id: 42,
  //   name: "E2",
  //   occupied: false,
  //   distances: [6, 6, 4],
  //   size: 2,
  // },
  // {
  //   id: 43,
  //   name: "E3",
  //   occupied: false,
  //   distances: [7, 4, 4],
  //   size: 2,
  // },
  // {
  //   id: 44,
  //   name: "E4",
  //   occupied: false,
  //   distances: [5, 4, 2],
  //   size: 0,
  // },
  // {
  //   id: 45,
  //   name: "E5",
  //   occupied: false,
  //   distances: [7, 1, 7],
  //   size: 1,
  // },
  // {
  //   id: 46,
  //   name: "E6",
  //   occupied: false,
  //   distances: [7, 1, 2],
  //   size: 0,
  // },
  // {
  //   id: 47,
  //   name: "E7",
  //   occupied: false,
  //   distances: [1, 3, 2],
  //   size: 0,
  // },
  // {
  //   id: 48,
  //   name: "E8",
  //   occupied: false,
  //   distances: [3, 2, 5],
  //   size: 0,
  // },
  // {
  //   id: 49,
  //   name: "E9",
  //   occupied: false,
  //   distances: [2, 7, 4],
  //   size: 2,
  // },
  // {
  //   id: 50,
  //   name: "E10",
  //   occupied: false,
  //   distances: [5, 3, 4],
  //   size: 1,
  // },
  // {
  //   id: 51,
  //   name: "F1",
  //   occupied: false,
  //   distances: [6, 3, 4],
  //   size: 1,
  // },
  // {
  //   id: 52,
  //   name: "F2",
  //   occupied: false,
  //   distances: [1, 6, 5],
  //   size: 0,
  // },
  // {
  //   id: 53,
  //   name: "F3",
  //   occupied: false,
  //   distances: [4, 5, 1],
  //   size: 0,
  // },
  // {
  //   id: 54,
  //   name: "F4",
  //   occupied: false,
  //   distances: [2, 3, 7],
  //   size: 1,
  // },
  // {
  //   id: 55,
  //   name: "F5",
  //   occupied: false,
  //   distances: [5, 4, 7],
  //   size: 1,
  // },
  // {
  //   id: 56,
  //   name: "F6",
  //   occupied: false,
  //   distances: [1, 3, 7],
  //   size: 1,
  // },
  // {
  //   id: 57,
  //   name: "F7",
  //   occupied: false,
  //   distances: [1, 6, 6],
  //   size: 1,
  // },
  // {
  //   id: 58,
  //   name: "F8",
  //   occupied: false,
  //   distances: [4, 6, 7],
  //   size: 2,
  // },
  // {
  //   id: 59,
  //   name: "F9",
  //   occupied: false,
  //   distances: [5, 6, 4],
  //   size: 2,
  // },
  // {
  //   id: 60,
  //   name: "F10",
  //   occupied: false,
  //   distances: [6, 6, 2],
  //   size: 1,
  // },
  // {
  //   id: 61,
  //   name: "G1",
  //   occupied: false,
  //   distances: [5, 5, 7],
  //   size: 2,
  // },
  // {
  //   id: 62,
  //   name: "G2",
  //   occupied: false,
  //   distances: [3, 2, 2],
  //   size: 1,
  // },
  // {
  //   id: 63,
  //   name: "G3",
  //   occupied: false,
  //   distances: [1, 7, 5],
  //   size: 2,
  // },
  // {
  //   id: 64,
  //   name: "G4",
  //   occupied: false,
  //   distances: [6, 1, 7],
  //   size: 1,
  // },
  // {
  //   id: 65,
  //   name: "G5",
  //   occupied: false,
  //   distances: [5, 4, 5],
  //   size: 1,
  // },
  // {
  //   id: 66,
  //   name: "G6",
  //   occupied: false,
  //   distances: [4, 5, 7],
  //   size: 0,
  // },
  // {
  //   id: 67,
  //   name: "G7",
  //   occupied: false,
  //   distances: [6, 3, 6],
  //   size: 0,
  // },
  // {
  //   id: 68,
  //   name: "G8",
  //   occupied: false,
  //   distances: [3, 4, 3],
  //   size: 2,
  // },
  // {
  //   id: 69,
  //   name: "G9",
  //   occupied: false,
  //   distances: [7, 5, 5],
  //   size: 0,
  // },
  // {
  //   id: 70,
  //   name: "G10",
  //   occupied: false,
  //   distances: [6, 1, 1],
  //   size: 1,
  // },
  // {
  //   id: 71,
  //   name: "H1",
  //   occupied: false,
  //   distances: [4, 3, 7],
  //   size: 1,
  // },
  // {
  //   id: 72,
  //   name: "H2",
  //   occupied: false,
  //   distances: [7, 1, 3],
  //   size: 2,
  // },
  // {
  //   id: 73,
  //   name: "H3",
  //   occupied: false,
  //   distances: [1, 1, 4],
  //   size: 2,
  // },
  // {
  //   id: 74,
  //   name: "H4",
  //   occupied: false,
  //   distances: [1, 2, 3],
  //   size: 2,
  // },
  // {
  //   id: 75,
  //   name: "H5",
  //   occupied: false,
  //   distances: [5, 2, 4],
  //   size: 1,
  // },
  // {
  //   id: 76,
  //   name: "H6",
  //   occupied: false,
  //   distances: [2, 7, 7],
  //   size: 1,
  // },
  // {
  //   id: 77,
  //   name: "H7",
  //   occupied: false,
  //   distances: [1, 5, 6],
  //   size: 1,
  // },
  // {
  //   id: 78,
  //   name: "H8",
  //   occupied: false,
  //   distances: [2, 5, 5],
  //   size: 1,
  // },
  // {
  //   id: 79,
  //   name: "H9",
  //   occupied: false,
  //   distances: [6, 6, 5],
  //   size: 2,
  // },
  // {
  //   id: 80,
  //   name: "H10",
  //   occupied: false,
  //   distances: [1, 3, 3],
  //   size: 1,
  // },
  // {
  //   id: 81,
  //   name: "I1",
  //   occupied: false,
  //   distances: [1, 3, 1],
  //   size: 0,
  // },
  // {
  //   id: 82,
  //   name: "I2",
  //   occupied: false,
  //   distances: [7, 1, 2],
  //   size: 1,
  // },
  // {
  //   id: 83,
  //   name: "I3",
  //   occupied: false,
  //   distances: [7, 2, 2],
  //   size: 1,
  // },
  // {
  //   id: 84,
  //   name: "I4",
  //   occupied: false,
  //   distances: [6, 7, 6],
  //   size: 0,
  // },
  // {
  //   id: 85,
  //   name: "I5",
  //   occupied: false,
  //   distances: [6, 5, 5],
  //   size: 0,
  // },
  // {
  //   id: 86,
  //   name: "I6",
  //   occupied: false,
  //   distances: [3, 3, 5],
  //   size: 2,
  // },
  // {
  //   id: 87,
  //   name: "I7",
  //   occupied: false,
  //   distances: [4, 4, 1],
  //   size: 1,
  // },
  // {
  //   id: 88,
  //   name: "I8",
  //   occupied: false,
  //   distances: [7, 3, 6],
  //   size: 1,
  // },
  // {
  //   id: 89,
  //   name: "I9",
  //   occupied: false,
  //   distances: [2, 2, 5],
  //   size: 0,
  // },
  // {
  //   id: 90,
  //   name: "I10",
  //   occupied: false,
  //   distances: [1, 5, 2],
  //   size: 2,
  // },
  // {
  //   id: 91,
  //   name: "J1",
  //   occupied: false,
  //   distances: [2, 4, 3],
  //   size: 2,
  // },
  // {
  //   id: 92,
  //   name: "J2",
  //   occupied: false,
  //   distances: [1, 4, 3],
  //   size: 0,
  // },
  // {
  //   id: 93,
  //   name: "J3",
  //   occupied: false,
  //   distances: [2, 1, 5],
  //   size: 2,
  // },
  // {
  //   id: 94,
  //   name: "J4",
  //   occupied: false,
  //   distances: [1, 3, 2],
  //   size: 1,
  // },
  // {
  //   id: 95,
  //   name: "J5",
  //   occupied: false,
  //   distances: [5, 5, 3],
  //   size: 0,
  // },
  // {
  //   id: 96,
  //   name: "J6",
  //   occupied: false,
  //   distances: [3, 5, 7],
  //   size: 0,
  // },
  // {
  //   id: 97,
  //   name: "J7",
  //   occupied: false,
  //   distances: [1, 6, 2],
  //   size: 2,
  // },
  // {
  //   id: 98,
  //   name: "J8",
  //   occupied: false,
  //   distances: [5, 4, 5],
  //   size: 0,
  // },
  // {
  //   id: 99,
  //   name: "J9",
  //   occupied: false,
  //   distances: [5, 7, 6],
  //   size: 2,
  // },
  // {
  //   id: 100,
  //   name: "J10",
  //   occupied: false,
  //   distances: [4, 6, 6],
  //   size: 2,
  // },
];
